---

# http://stackoverflow.com/a/24765946

- name: create swap file
  command: dd if=/dev/zero of="{{ swap_file }}" bs="{{ swap_block_size }}" count="{{ swap_block_count }}"
  args:
    creates: "{{ swap_file }}"
  
- name: set swap file permission
  file: path="{{ swap_file }}" owner=root group=root mode=0600

- name: check swap file type
  command: file {{ swap_file }}
  register: swap_file_type

- name: make swap file
  command: mkswap "{{ swap_file }}"
  when: swap_file_type.stdout.find('swap file') == -1

- name: fstab swap
  mount: name=none src="{{ swap_file }}" fstype=swap opts=sw passno=0 dump=0 state=present

- name: mount swap
  command: swapon -a {{ swap_file }}
  when: ansible_swaptotal_mb < 1
