---

- name: create users
  user: name={{ item.name }} groups={{ ','.join(item.groups) }} shell={{ item.shell }} state=present
  with_items: users

- name: authorize user keys
  authorized_key: "user={{ item.0.name }} key='{{ item.1 }}' state=present"
  with_subelements:
    - users
    - authorized_keys

- name: sudoer
  template: "src=50-sudoer.j2 dest=/etc/sudoers.d/50-{{ sudoer }} owner=root group=root mode=0440"

- name: set security limits
  template: "src=limits.conf.j2 dest=/etc/security/limits.conf owner=root group=root mode=0440"
