---

- name: create users
  user: name="{{ item.name }}" groups="{{ ','.join(item.groups) }}" shell="{{ item.shell }}" state=present
  with_items: users

- name: authorize keys
  authorized_key: user="{{ item.0.name }}" key="{{ item.1 }}" state=present
  with_subelements:
    - users
    - authorized_keys

- name: revoke keys
  authorized_key: user="{{ item.0.name }}" key="{{ item.1 }}" state=absent
  with_subelements:
    - users
    - revoked_keys

- name: delete users
  user: name="{{ item.name }}" state=absent
  with_items: deleted_users

- name: sudoer
  template: src=50-sudoer.j2 dest="/etc/sudoers.d/50-{{ sudoer }}" owner=root group=root mode=0440

- name: security limits
  template: src=limits.conf.j2 dest=/etc/security/limits.conf owner=root group=root mode=0440

- name: copy user files
  copy: src=users/ dest=/home
  with_items: users
